spring:
  application:
    name: Adtech-Flinkboot
  threads:
    virtual:
      enabled: true
  kafka:
    bootstrap-servers:
      - localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        spring.json.add.type.headers: false

adtech:
  scenarios:
    pattern: "classpath*:scenarios/*.json"
  kafka:
    topics:
      campaign:
        budgets: campaign_budgets
      ad:
        impressions: ad_impressions
        clicks: ad_clicks
      conversion:
        events: conversions
